### ISSUE TITLE
Typecheck the Svelte layer: inertia/** is excluded from tsc

### ISSUE THREAD

**Issue by Thomasevano** [Thomasevano/musickeeper#52]
## Problem

`tsconfig.json` sets `"exclude": ["./inertia/**/*", "node_modules", "build"]`, so `pnpm run typecheck` (`tsc --noEmit`) never looks at a single Svelte file. The entire frontend is unchecked.

Found while wiring the `ListenLaterStorage` seam: `inertia/pages/listen-later.svelte` and `inertia/components/trackItem.svelte` were rewritten to call a typed store, and `tsc` had nothing to say about either. The only thing that would have caught a wrong field name or a missing required property was the Playwright suite — which does catch a lot here, but at 55 seconds a run and only along paths a test happens to exercise.

The store's input type makes this concrete: `add` takes `Omit<ListenLaterItemProperties, 'hasBeenListened' | 'addedAt'>`, where `id`, `title`, `releaseDate`, `artists` and `itemType` are all required. Both callers construct that object literal by hand, in unchecked files.

## Direction

Add `svelte-check` and a script (`"check": "svelte-check --tsconfig ./tsconfig.json"`), or a second tsconfig that includes `inertia/**` with the Svelte plugin. The repo already has `svelte.config.js` and `prettier-plugin-tailwindcss`, but no `prettier-plugin-svelte` and no `svelte-check`.

## First task is to measure, not to fix

Nobody has ever typechecked these files, so the error count is unknown and could be large. Before committing to a gate:

1. Install `svelte-check`, run it once, and report the error count in this issue.
2. Then decide: fix everything and gate CI, or gate at a baseline and burn the list down.

Do not silently add a gate that fails, and do not blanket-suppress to make it green.

## Acceptance

- The error count is known and recorded here.
- A decision is taken on gating, with a reason.
- If gated: `pnpm run lint`, `pnpm run typecheck`, the new check, `pnpm test` and `pnpm run test:e2e` all pass.

**Comment by Thomasevano** [comment]
## A dead end, so nobody repeats it

The AdonisJS v7 branch (#33) briefly carried a partial attempt at this: a `tsconfig.inertia.json` composite project, pulled in from the root `tsconfig.json` as a project reference.

```jsonc
// tsconfig.inertia.json
{
  "extends": "./inertia/tsconfig.json",
  "compilerOptions": { "rootDir": "./inertia", "composite": true },
  "include": ["./inertia/**/*.ts", "./inertia/**/*.svelte"]
}

// tsconfig.json
"references": [{ "path": "./tsconfig.inertia.json" }],
"exclude": ["./inertia/**/*", "node_modules", "build"]
```

It was removed during the rebase onto `main`, for two reasons.

**It typechecked nothing.** Nothing ever built it — `typecheck` is `tsc --noEmit`, not `tsc -b`, and no `.tsbuildinfo` was gitignored. A reference alone does not make the referenced project run.

**It actively broke `pnpm typecheck`.** Once `main` landed `tests/unit/inertia/components/data-table/data_table_row_transitions.spec.ts`, which imports `inertia/components/data-table/data_table_row_transitions.js`, the reference reclassified that import as belonging to a composite project. TypeScript then demanded a prebuilt declaration instead of reading the source:

```
tests/unit/inertia/components/data-table/data_table_row_transitions.spec.ts(5,8):
error TS6305: Output file '.../data_table_row_transitions.d.ts' has not been built
from source file '.../data_table_row_transitions.ts'
```

Note the trap: on `main`, `exclude` does **not** stop that test from typechecking its import — `exclude` only filters root-file globbing, not files reached through imports. So the reference turned a working typecheck into a failing one, while still leaving every `.svelte` file unchecked.

## What this implies for the fix

A bare project reference is not enough. Whichever route is taken has to be a real, run gate:

- **`tsc -b`** — then `typecheck` must become a build, `tsconfig.inertia.json` needs a `declarationDir`/`outDir` outside the source tree, and that output plus `*.tsbuildinfo` must be gitignored. Still does not read `<script lang="ts">` inside `.svelte`.
- **`svelte-check`** — the only option that actually typechecks component markup and script blocks. `svelte-language-server` is already a devDependency, so `svelte-check` is a small addition. Likely a separate script (`typecheck:svelte`) wired into CI beside `typecheck`.

The problem statement in this issue is unchanged: `inertia/**` is still outside `tsc`, exactly as before the upgrade. #33 neither fixes nor worsens it.

**Comment by Thomasevano** [comment]
Note from the v7 / Inertia v3 upgrade ([#33](https://github.com/Thomasevano/musickeeper/pull/33)).

The v7 commit originally added a `tsconfig.inertia.json` plus a project reference from the root `tsconfig.json`, which looked like a partial answer to this issue. It was removed while rebasing the branch onto `main`:

- nothing built it — `pnpm typecheck` is `tsc --noEmit`, which ignores referenced projects unless they are built;
- it broke the gate — once `main`'s `tests/unit/inertia/components/data-table/data_table_row_transitions.spec.ts` landed, `tsc --noEmit` failed with TS6305 (output file not built from the referenced source).

So `exclude: ["./inertia/**/*", …]` is untouched by #33 and this issue stands exactly as written.

Two things the fix should account for, both new since this issue was filed:

- The real coverage for `.svelte` files is `svelte-check`, not `tsc`; a project reference alone would still only check the `.ts` files under `inertia/`.
- Adonis Inertia 5 exposes client-side shared-prop typing: `declare module '@inertiajs/core' { interface InertiaConfig { sharedPageProps: … } }`, fed from `InferSharedProps<InertiaMiddleware>`. Nothing declares it today, which is why `page.props.title` in `inertia/layouts/layout.svelte` is untyped. Worth wiring in the same change.

**Comment by Thomasevano** [comment]
## Measured: 13 errors, 1 warning, 7 files

Ran `svelte-check` against `inertia/tsconfig.json` with no code or config changes, on `chore/adonisjs-v7` (`e005437`, post-Inertia-v3):

```
pnpm dlx svelte-check --tsconfig ./inertia/tsconfig.json
svelte-check found 13 errors and 1 warning in 7 files
```

5178 files scanned in **4.6s**. That runtime matters: it's cheap enough to be a real gate, unlike the 55s Playwright suite the problem statement leans on today.

### The 13

| # | Where | Error | Class |
|---|---|---|---|
| 4 | `app.ts` (×3), `app.ts:3` | `import.meta.env` / `import.meta.glob` missing; CSS side-effect import unresolved | **config** |
| 1 | `ssr.ts:8` | `import.meta.glob` missing | **config** |
| 3 | `lib/helpers/load_more.ts:2`, `components/ConfirmMusicDialog.svelte:11`, `pages/listen-later.svelte:17` | `Cannot find module '../../src/domain/playlist'` / `'../../src/infrastructure/services/link_metadata.service'` | **rot** |
| 2 | `app.ts:22`, `app.ts:24` | `createInertiaApp` — no overload matches | **Inertia v3** |
| 2 | `app.ts:21`, `ssr.ts:11` | `'el' is possibly 'null'`; `'el' declared but never read` | **genuine** |
| 1 | `lib/components/ui/badge/badge.svelte:46` | `ClassValue` not assignable to `ClassNameValue` | **dep skew** |

Plus one warning: `baseUrl` is deprecated and stops working in TS 7.0.

**The five config errors are one line.** `@adonisjs/tsconfig/tsconfig.client.json` sets `"types": ["vite/client"]`, and `inertia/tsconfig.json` *replaces* rather than extends it with `"types": ["vite-plugin-pwa/client"]`. So Vite's ambient types were never loaded. Fix is `"types": ["vite/client", "vite-plugin-pwa/client"]`.

**The three "rot" errors are the ones that justify the issue.** Neither `src/domain/playlist` nor `src/infrastructure/services/link_metadata.service` exists anywhere in the tree — `find src app` returns nothing for either. `PaginatedPlaylistsInfos` and `LinkMetadata` are imported `import type`, so Vite strips them and runtime is unaffected; three type contracts have been silently `any` since the clean-architecture move. This is exactly the failure mode the problem statement predicted, found without a single test being written.

## Decision: fix everything, then gate. No baseline.

13 is not a burn-down list, it's an afternoon. A baseline file would cost more to maintain than the errors cost to fix, and it would institutionalise the three dead imports as "known". Gate on zero.

Reasons this is safe to gate at zero:

- Five of thirteen are one config line.
- Two are dead-import fallout with a bounded fix (relocate the types or reconstruct them at their new home).
- The 4.6s runtime keeps it off the critical path in CI.

## Sequencing caveat: land this on top of the v7 branch, not before it

Two of the thirteen (`createInertiaApp` overloads) are artefacts of `e005437`, which adopted Inertia v3 — they don't exist on `main`. Gating `main` first means #33 lands into a gate it fails. Do this after #33 merges, or as a commit on that branch.

## Remaining work

- [ ] `"types": ["vite/client", "vite-plugin-pwa/client"]` in `inertia/tsconfig.json` — clears 5
- [ ] Repoint or reconstruct `PaginatedPlaylistsInfos` and `LinkMetadata` — clears 3
- [ ] `createInertiaApp` overloads under Inertia v3 — clears 2
- [ ] `el` null-guard + unused binding — clears 2
- [ ] `badge.svelte` `ClassValue`/`ClassNameValue` skew — clears 1
- [ ] `ignoreDeprecations` or drop `baseUrl` — clears the warning
- [ ] Add `svelte-check` as a devDependency and a `typecheck:svelte` script; wire into CI beside `typecheck`

Acceptance criteria 1 and 2 are now met. Re-labelled `ready-for-agent`.

**Comment by Thomasevano** [comment]
Cross-referencing [the comment above](https://github.com/Thomasevano/musickeeper/issues/52#issuecomment-5272378345) — it landed 19s before my measurement, so the count doesn't account for it.

Its shared-prop point is verified and adds an eighth work item:

- `@inertiajs/core/types/types.d.ts:81` exposes `interface InertiaConfig { sharedPageProps }`. Nothing in this repo augments it.
- `src/infrastructure/http/middleware/inertia_middleware.ts:32` augments `SharedProps` on `@adonisjs/inertia/types` — server side only. The client half is missing, so `page.props.title` in `inertia/layouts/layout.svelte:10` is unchecked.

**svelte-check cannot report this.** Untyped `page.props` is `any`, and `any` raises no error — which is why it is absent from the 13. Gating at zero is still correct, but zero covers less than it appears to while every page's props are invisible.

**Expect the count to rise when it's wired.** `share()` returns only `errors`, `appName`, `appVersion`. `layout.svelte` reads `title` and `description`, neither of which is shared — so declaring `sharedPageProps` from `InferSharedProps<InertiaMiddleware>` should turn both reads red. That is the gate working, not a regression; budget for it.

Added to remaining work:

- [ ] `declare module '@inertiajs/core' { interface InertiaConfig { sharedPageProps: SharedProps } }` on the client, fed from the existing `InferSharedProps<InertiaMiddleware>`; resolve the `title`/`description` reads it exposes.
